# Generated by Django 3.2.9 on 2021-11-24 03:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('friends', models.ManyToManyField(related_name='_Main_myuser_friends_+', to='Main.MyUser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.myuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='UsersTags',
            field=models.ManyToManyField(related_name='users_tags', to='Main.MyUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
